# Generated by Django 6.0.8 on 2026-09-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
